site:
  title: NATS Documentation
  url: https://hooksie1.github.io/nats-documentation/
  start_page: nats-documentation::index.adoc

content:
  sources:
  - url: "."
    branches: main
    start_path: docs
  - url: "https://github.com/hooksie1/nats.go"
    branches: documentation-site
    start_path: docs
  - url: "https://github.com/hooksie1/nats.py"
    branches: documentation-site
    start_path: docs

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental

asciidoc:
  attributes:
    experimental: ''
